### ISSUE TITLE
Missing galician translation in micromouse competition rules

### ISSUE THREAD

**Issue by Peque** [brico-labs/Regulamentos#7]
In particular in the 10th item of the maze rules. Missing translation for:

> La salida está orientada de manera que cuando la pared libre se encuentra al "norte", las paredes de contorno del laberinto se encuentran al "oeste" y "sur". Es decir, el robot sale en sentido de las agujas del reloj.

This change was included in https://github.com/brico-labs/Regulamentos/commit/23ece285de97967092817d3a1c26b54a61a0d701 but galician translation was missing.

**Comment by Scraw** [comment]
Just translated. Thanks for your help!
